server:
  port: 10988
  servlet:
    context-path: /tankBattleBP
  tomcat:
    threads:
      max: 20000


  application:
    name: tankBattleBP

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:/mapping*/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zq.tankbattle.entity  # 注意：对应实体类的路径



##分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

logging:
  level:
    root: debug
  config: classpath:logback-spring.xml



